---
title: "June 2016 EDA"
author: "Aidan Mullan"
date: "2/21/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This Rmd conducts EDA on Yellow Cab taxi data for the month of June 2016, which serves as a snapshot for the overall dataset. All code written here could easily be used for any other month by replacing the dataset that is imported.

```{r}
library(rvest)
library(xml2)
library(magrittr)
library(stringr)
library(tidyr)
library(ggplot2)
library(ggmap)
library(gridExtra)
library(cowplot)


## Retrieving yellow taxi data for June 2016
URL <- "https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page"

links <- read_html(URL) %>% html_nodes("a") %>% html_attr('href')

## Subset to only yellow cab datasets
yellow_index <- str_detect(links, "yellow_tripdata")
yellow_data <- links[yellow_index]
june2016 <- read.csv(yellow_data[24])
```

```{r}
###
### Cleaning data file to have desired values
###

## Extract day/time/lat+long of pickup + dropoff, and distance
sub_june2016 <- june2016[,c(2,3,6,7,10,11)]

## Split datetime variables into separate day and time variables
firstsplit_june2016 <- sub_june2016 %>% separate(tpep_pickup_datetime, sep = " ", n = 2,
                                                 into = c("pickup_date", "pickup_time")) %>%
                                        separate(tpep_dropoff_datetime, sep = " ", n = 2,
                                                 into = c("dropoff_date", "dropoff_time"))

## Split time into hour, minute, second and split day into year, month, and day
clean_june2016 <- firstsplit_june2016 %>% separate(pickup_time, sep = ":", n = 3,
                                                  into = c("PU_hour", "PU_minute", "PU_second")) %>%
                                         separate(pickup_date, sep = "-", n = 3,
                                                  into = c("PU_year", "PU_month", "PU_day")) %>%
                                         separate(dropoff_time, sep = ":", n = 3,
                                                  into = c("DO_hour", "DO_minute", "DO_second")) %>%
                                         separate(dropoff_date, sep = "-", n = 3,
                                                  into = c("DO_year", "DO_month", "DO_day"))

names(clean_june2016)
```

```{r, warning=FALSE}
###
## Extracting lat/long of dropoff and pickup
###

## Subset to all pickups between 12 and 1
pu_june2016_raw <- subset(clean_june2016, subset = PU_hour == 12 & PU_minute <= 30)[,c(3:5,9:11,13:16)]
pu_june2016 <- pu_june2016_raw[,c(1:3,7:8)]
pu_june2016 <- subset(pu_june2016, subset = pickup_latitude != 0 & pickup_longitude != 0)

do_june2016_raw <- subset(clean_june2016, subset = DO_hour == 12 & DO_minute <= 30)[,c(3:5,9:11,13:16)]
do_june2016 <- do_june2016_raw[,c(4:6,9:10)]
do_june2016 <- subset(do_june2016, subset = dropoff_latitude != 0 & dropoff_longitude != 0)

## Retreive average latitude/longitude
pu_mean_lat <- mean(pu_june2016$pickup_latitude)
pu_mean_long <- mean(pu_june2016$pickup_longitude)

do_mean_lat <- mean(do_june2016$dropoff_latitude)
do_mean_long <- mean(do_june2016$dropoff_longitude)


## Heatmaps for overall pu/do and for Manhattan only
pu_map_raw <- get_map(location = c(pu_mean_long, pu_mean_lat), zoom = 11, scale = 2)
pu_map <- ggmap(pu_map_raw, legend = "none")
pu_heatmap <- pu_map + geom_point(data = pu_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = pickup_longitude, y = pickup_latitude)) + 
  ggtitle("New York City Pickups on June 2016 at Noon") + 
  theme(text = element_text(size = 15), axis.text = element_blank(), axis.ticks = element_blank(),
        axis.line = element_blank()) + 
  labs(x = "", y = "")

pu_map_raw2 <- get_map(location = c(pu_mean_long, pu_mean_lat), zoom = 12, scale = 2)
pu_map2 <- ggmap(pu_map_raw2, legend = "none")
pu_densitymap <- pu_map2 + geom_point(data = pu_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = pickup_longitude, y = pickup_latitude)) + 
  ggtitle("Manhattan Pickups on June 2016 at Noon") + 
  theme(text = element_text(size = 15), axis.text = element_blank(), axis.ticks = element_blank(),
        axis.line = element_blank()) + 
  labs(x = "", y = "")

do_map_raw <- get_map(location = c(do_mean_long, do_mean_lat), zoom = 11, scale = 2)
do_map <- ggmap(do_map_raw, legend = "none")
do_heatmap <- do_map + geom_point(data = do_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = dropoff_longitude, y = dropoff_latitude)) + 
  ggtitle("New York City Dropoffs on June 2016 at Noon") + 
  theme(text = element_text(size = 15), axis.text = element_blank(), axis.ticks = element_blank(),
        axis.line = element_blank()) + 
  labs(x = "", y = "")

do_map_raw2 <- get_map(location = c(do_mean_long, do_mean_lat), zoom = 12, scale = 2)
do_map2 <- ggmap(do_map_raw2, legend = "none")
do_densitymap <- do_map2 + geom_point(data = do_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = dropoff_longitude, y = dropoff_latitude)) + 
  ggtitle("Manhattan Dropoffs on June 2016 at Noon") + 
  theme(text = element_text(size = 15), axis.text = element_blank(), axis.ticks = element_blank(),
        axis.line = element_blank()) + 
  labs(x = "", y = "")

do_heatmap; do_densitymap; pu_heatmap; pu_densitymap

ovr_heatmap <- pu_map + geom_point(data = do_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = dropoff_longitude, y = dropoff_latitude)) +
                           geom_point(data = pu_june2016, alpha = 0.05, size = 0.1,
                                  aes(x = pickup_longitude, y = pickup_latitude)) + 
  ggtitle("NY Dropoffs and Pickups on June 2016 at Noon") + 
  theme(text = element_text(size = 15), axis.text = element_blank(), axis.ticks = element_blank(),
        axis.line = element_blank()) + 
  labs(x = "", y = "")
  
ovr_heatmap; pu_heatmap
```
