---
title: 'Mon12 Analysis'
author: "Aidan Mullan"
date: "4/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(caret)
library(dplyr)
library(e1071)
library(geohash)
library(stringr)
library(ggplot2)
library(ggmap)
```


```{r}
## Read in data for each year, add year into column names
nd09 <- read.csv("Data/NetDiff_Mon12/netdiff2009.csv")[,-1]
names(nd09) <- c("geohash", "Jan09", "Feb09", "Mar09", "Apr09", "May09", "Jun09", "Jul09", "Aug09",
                 "Sep09", "Oct09", "Nov09", "Dec09")
nd10 <-  read.table("Data/NetDiff_Mon12/netdiff2010", sep = ",", header = TRUE)[,-1]
names(nd10) <- c("geohash", "Jan10", "Feb10", "Mar10", "Apr10", "May10", "Jun10", "Jul10", "Aug10",
                 "Sep10", "Oct10", "Nov10", "Dec10")
temp11_13 <-  read.table("Data/NetDiff_Mon12/netdiff201113,csv", sep = ",", header = TRUE)[,-1]
nd11 <- temp11_13[,1:13]; nd12 <- temp11_13[,c(1,14:25)]; nd13 <- temp11_13[,c(1,26:36)]
names(nd11) <- c("geohash", "Jan11", "Feb11", "Mar11", "Apr11", "May11", "Jun11", "Jul11", "Aug11",
                 "Sep11", "Oct11", "Nov11", "Dec11")
names(nd12) <- c("geohash", "Jan12", "Feb12", "Mar12", "Apr12", "May12", "Jun12", "Jul12", "Aug12",
                 "Sep12", "Oct12", "Nov12", "Dec12")
names(nd13) <- c("geohash", "Jan13", "Feb13", "Mar13", "Apr13", "May13", "Jun13", "Jul13", "Aug13",
                 "Sep13", "Oct13", "Nov13")
nd14 <- read.csv("Data/NetDiff_Mon12/netdiff2014.csv")[,-1]
names(nd14) <- c("geohash", "Jan14", "Feb14", "Mar14", "Apr14", "May14", "Jun14", "Jul14", "Aug14",
                 "Sep14", "Oct14", "Nov14", "Dec14")
nd15 <- read.csv("Data/NetDiff_Mon12/netdiff15.csv")[,-1]
names(nd15) <- c("geohash", "Jan15", "Feb15", "Mar15", "Apr15", "May15", "Jun15", "Jul15", "Aug15",
                 "Sep15", "Oct15", "Nov15", "Dec15")
nd16 <- read.csv("Data/NetDiff_Mon12/netdiff2016")[,-1]
names(nd16) <- c("geohash", "Jan16", "Feb16", "Mar16", "Apr16", "May16", "Jun16")
```

```{r}
## Merge data from each year by geohash ID
nd09_10 <- merge(nd09, nd10, by = "geohash", all = TRUE)
nd09_11 <- merge(nd09_10, nd11, by = "geohash", all = TRUE)
nd09_12 <- merge(nd09_11, nd12, by = "geohash", all = TRUE)
nd09_13 <- merge(nd09_12, nd13, by = "geohash", all = TRUE)
nd09_14 <- merge(nd09_13, nd14, by = "geohash", all = TRUE)
nd09_15 <- merge(nd09_14, nd15, by = "geohash", all = TRUE)
nd09_16 <- merge(nd09_15, nd16, by = "geohash", all = TRUE)

## Identify months where a cell had no data
miss_index <- is.na(nd09_16[,-1])
nd09_16[is.na(nd09_16)] <- 0

## For each cell, count number of months with no data
miss_counts <- 89 - rowSums(miss_index)
full_counts <- which(miss_counts == 89)
half_counts <- which(miss_counts >= 50)

## Retrieve all cells that never missed data
full09_16 <- nd09_16[full_counts,]
half09_16 <- nd09_16[half_counts,]
```

```{r, eval = FALSE}
## EDA for time series
set.seed(123456)
size <- length(full09_16[,1])
index <- sample(size, 1)
sample <- as.vector(full09_16[index,-1])
plot(1:89,sample[1,1:89], type = "l")


## Analyzing linear trend for all cell time series
trend <- predicts <- numeric(size)
for(i in 1:size){
  counts <- numeric(89)
  for(j in 1:89){
    counts[j] <- full09_16[i,j+1]
  }
  time <- 1:89
  trend_model <- lm(counts~time)
  trend[i] <- trend_model$coef[2]
  #predict_model <- lm(counts[-89]~time[-89])
  #predicts[i] <- predict_model$coef[1] + 89*predict_model$coef[2]
}
summary(trend)
hist(trend, breaks = 30)
#mse_predict <- mean((full09_16[,90] - predicts)^2) ## 182.918

## Plotting TS for mix/max linear trend
max_cell <- full09_16[which.max(trend),]
plot(1:89,max_cell[2:90], type = "l")
min_cell <- full09_16[which.min(trend),]
plot(1:89,min_cell[2:90], type = "l")
```

```{r, eval = FALSE}
## Basic KNN to predict June 2016
MayJun_16 <- nd09_16[,c(1,89,90)]
hashes <- gh_decode(MayJun_16$geohash)
MayJun_16$Longitude <- hashes$lng
MayJun_16$Latitude <- hashes$lat
MayJun_16$Long0 <- scale(MayJun_16$Longitude)
MayJun_16$Lat0 <- scale(MayJun_16$Latitude)

size <- length(Jun_16[,1])
train_size <- size * 0.8
train_index <- sample(size, train_size)
train_data <- MayJun_16[train_index,]
test_data <- MayJun_16[-train_index,]

Jun16_control <- trainControl(method = "cv", number = 10, classProbs = TRUE)
Jun16_knn <- train(Jun16~Long0+Lat0, data = train_data, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
Jun16_knn # k = 4, RMSE = 9.701, Rsq = 0.544

Jun16_preds <- predict(Jun16_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - Jun16_preds)^2)) # 14.462

#####---------------------------------
## Using May 2016 to predict June 2016
MayJun16_knn <- train(May16~Long0+Lat0, data = MayJun_16, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
MayJun16_knn # k = 4, RMSE = 12.772, Rsq = 0.550

MayJun_preds <- predict(MayJun16_knn, newdata = MayJun_16[,c(3,6,7)])
sqrt(mean((MayJun_16$Jun16 - MayJun_preds)^2)) # RMSE = 20.642

MayJun_preds2 <- predict(MayJun16_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - MayJun_preds2)^2)) # RMSE = 9.437

#####-------------------------------------
## Using Average from 2009-2016: All Months

MayJun_16$AllMeans <- rowMeans(nd09_16[,-c(1,90)])
AllMeans_knn <- train(AllMeans~Long0+Lat0, data = MayJun_16, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
AllMeans_knn # k = 4, RMSE = 11.619, Rsq = 0.643

AllMeans_preds <- predict(AllMeans_knn, newdata = MayJun_16[,c(3,6,7)])
sqrt(mean((MayJun_16$Jun16 - AllMeans_preds)^2)) # RMSE = 9.569

AllMeans_preds2 <- predict(AllMeans_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - AllMeans_preds2)^2)) # RMSE = 10.034

#####-------------------------------------
## Using Average from 2009-2016: June Only

MayJun_16$JuneMeans <- rowMeans(nd09_16[,c(7,19,31,43,55,66,78)])
JuneMeans_knn <- train(JuneMeans~Long0+Lat0, data = MayJun_16, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
JuneMeans_knn # k = 4, RMSE = 12.209, Rsq = 0.664

JuneMeans_preds <- predict(JuneMeans_knn, newdata = MayJun_16[,c(3,6,7)])
sqrt(mean((MayJun_16$Jun16 - JuneMeans_preds)^2)) # RMSE = 10.428

JuneMeans_preds2 <- predict(JuneMeans_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - JuneMeans_preds2)^2)) # RMSE = 10.944
```

```{r, eval = FALSE}
## Determining RSME for Prediction of All 2016 Months under 3 Methods

Months16 <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
RMSE <- data.frame(Prev_Month = numeric(6), AllMeans = numeric(6), MonthMeans = numeric(6))
i = 1
for(month in Months16){
  test_name <- str_c(month, "16")
  test_id <- which(names(nd09_16) == test_name)
  prev_id <- test_id-1
  model_data <- nd09_16[,c(1,prev_id, test_id)]
  names(model_data) <- c("geohash", "Prev_Month", "Test_Month")
  
  hashes <- gh_decode(model_data$geohash)
  model_data$Longitude <- scale(hashes$lng)
  model_data$Latitude <- scale(hashes$lat)
  
  model_data$AllMeans <- rowMeans(nd09_16[,2:prev_id])
  all_months <- str_detect(names(nd09_16)[-c(85:90)], month)
  model_data$MonthMeans <- rowMeans(nd09_16[,all_months])
  
  control <- trainControl(method = "cv", number = 10, classProbs = TRUE)
  PMonth_knn <- train(Prev_Month~Longitude+Latitude, data = model_data, method = "knn",
                trControl = control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
  AllMeans_knn <- train(AllMeans~Longitude+Latitude, data = model_data, method = "knn",
                trControl = control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
  MonthMeans_knn <- train(MonthMeans~Longitude+Latitude, data = model_data, method = "knn",
                trControl = control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
  
  PMonth_preds <- predict(PMonth_knn, newdata = model_data[,3:5])
  RMSE$Prev_Month[i] <- sqrt(mean((model_data$Test_Month - PMonth_preds)^2))
  AllMeans_preds <- predict(AllMeans_knn, newdata = model_data[,3:5])
  RMSE$AllMeans[i] <- sqrt(mean((model_data$Test_Month - AllMeans_preds)^2))
  MonthMeans_preds <- predict(MonthMeans_knn, newdata = model_data[,3:5])
  RMSE$MonthMeans[i] <- sqrt(mean((model_data$Test_Month - MonthMeans_preds)^2))
  i <- i + 1
}

```

```{r, eval = FALSE}
#####-------------------
## Maps of Observed Data
#####-------------------

MayJun_16$AllMeans <- rowMeans(nd09_16[,-c(1,90)])
control <- trainControl(method = "cv", number = 10, classProbs = TRUE)
AllMeans_knn <- train(AllMeans~Longitude+Latitude, data = MayJun_16, method = "knn",
                trControl = control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")

MayJun_16$JunePreds <- predict(AllMeans_knn, newdata = MayJun_16[,3:5])

#####----------------
## Full Map of NYC

mlat <- mean(MayJun_16$Latitude)
mlon <- mean(MayJun_16$Longitude)
map_raw <- get_map(location = c(mlon, mlat), zoom = 11, scale = 2)
map <- ggmap(map_raw, legend = "none")

obs_midrange <- quantile(MayJun_16$Jun16, probs = c(.05, .95))
MayJun_16$obscolor <- cut(MayJun_16$Jun16,
                          breaks = c(-300, -15,-1,0,14,200),
                          labels = c("(-229,-15)", "(-14,-1)", "0", "(1,14)", "(15,200)"))

observed_map <- map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))
observed_map

##------------------------
## Zoomed Map of Manhattan
zoom_map_raw <- get_map(location = c(-73.96, 40.76), zoom = 12, scale = 2)
zoom_map <- ggmap(zoom_map_raw, legend = "none")
zoom_obs_map <- zoom_map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))
zoom_obs_map

##----------------------
## Split Maps of Positive v. Negative NetDiff

Jun16_pos <- subset(MayJun_16, subset = Jun16 >= 0)
Jun16_neg <- subset(MayJun_16, subset = Jun16 < 0)

zoom_pos_map <- zoom_map + geom_point(data = Jun16_pos, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor)) + 
  scale_color_manual(values = c("grey", "dodgerblue", "navyblue"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_neg_map <- zoom_map + geom_point(data = Jun16_neg, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_pos_map; zoom_neg_map
```

```{r, eval = FALSE}
#####-----------------------
## Maps of Predicted Data
#####-----------------------

pred_midrange <- quantile(MayJun_16$JunePreds, probs = c(.05, .95))
MayJun_16$predcolor <- cut(MayJun_16$JunePreds,
                          breaks = c(-300, -14.5,-1,0,14.5,200),
                          labels = c("(-229,-15)", "(-14,-1)", "0", "(1,14)", "(15,200)"))

predict_map <- map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))
predict_map; observed_map

##------------------------
## Zoomed Map of Manhattan Predictions

zoom_pred_map <- zoom_map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))
zoom_pred_map; zoom_obs_map

##----------------------
## Split Maps of Predicted Positive v. Negative NetDiff

Jun16_pospred <- subset(MayJun_16, subset = JunePreds >= -.5)
Jun16_negpred <- subset(MayJun_16, subset = JunePreds < -.5)

zoom_pospred_map <- zoom_map + geom_point(data = Jun16_pospred, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor)) + 
  scale_color_manual(values = c("grey", "dodgerblue", "navyblue"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_negpred_map <- zoom_map + geom_point(data = Jun16_negpred, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_pospred_map; zoom_pos_map
zoom_negpred_map; zoom_neg_map
```

```{r, eval = FALSE}
#####---------------------------
## Maps With Larger "Grey" Range
#####---------------------------

MayJun_16$obscolor2 <- cut(MayJun_16$Jun16,
                          breaks = c(-300, -15,-4,0,3,200),
                          labels = c("(-229,-15)", "(-14,-4)", "(-3,3)", "(4,14)", "(15,200)"))
MayJun_16$predcolor2 <- cut(MayJun_16$JunePreds,
                          breaks = c(-300, -14.5,-3,3,14.5,200),
                          labels = c("(-229,-15)", "(-14,-4)", "(-3,3)", "(4,14)", "(15,200)"))

#####-----------------------
## Full Scale Maps

observed_map2 <- map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

predict_map2 <- map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

observed_map2; predict_map2
#####----------------
## Zoomed Maps

zoom_obs_map2 <- zoom_map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_pred_map2 <- zoom_map + geom_point(data = MayJun_16, size = 0.03, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_pred_map2; zoom_obs_map2
#####----------------
## Split Pos/Neg Maps

Jun16_pos2 <- subset(MayJun_16, subset = Jun16 >= 0)
Jun16_neg2 <- subset(MayJun_16, subset = Jun16 < 0)
Jun16_pospred2 <- subset(MayJun_16, subset = JunePreds >= -.5)
Jun16_negpred2 <- subset(MayJun_16, subset = JunePreds < -.1)

zoom_pos_map2 <- zoom_map + geom_point(data = Jun16_pos2, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor2)) + 
  scale_color_manual(values = c("grey", "dodgerblue", "navyblue"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_neg_map2 <- zoom_map + geom_point(data = Jun16_neg2, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = obscolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))



zoom_pospred_map2 <- zoom_map + geom_point(data = Jun16_pospred2, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor2)) + 
  scale_color_manual(values = c("grey", "dodgerblue", "navyblue"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_negpred_map2 <- zoom_map + geom_point(data = Jun16_negpred2, size = 0.3, na.rm = TRUE, shape = 0,
                                       aes(x = Longitude, y = Latitude, color = predcolor2)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey"), name = "Net Pickups") +
  ggtitle("") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 5),
        legend.title = element_text(size = 5), legend.text = element_text(size = 4))

zoom_pospred_map2; zoom_pos_map2
zoom_negpred_map2; zoom_neg_map2
```

```{r}
#### Subset to Only Manhattan
full_hash <- gh_decode(nd09_16$geohash)
nd09_16$Lat <- full_hash$lat
nd09_16$Lon <- full_hash$lng

Jun16 <- nd09_16[,c(1,89:92)]
Jun16_Manhat <- subset(Jun16, subset = Lat >= 40.7 & Lat <= 40.84 & Lon >= -74.025 & Lon <= -73.92)
Jun16_Manhat$Long0 <- scale(Jun16_Manhat$Lon)
Jun16_Manhat$Lat0 <- scale(Jun16_Manhat$Lat)

size <- length(Jun16_Manhat[,1])
train_size <- size * 0.8
train_index <- sample(size, train_size)
train_data <- Jun16_Manhat[train_index,]
test_data <- Jun16_Manhat[-train_index,]

Jun16_control <- trainControl(method = "cv", number = 10, classProbs = TRUE)
Jun16_knn <- train(Jun16~Long0+Lat0, data = train_data, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
Jun16_knn # k = 4, RMSE = 9.701, Rsq = 0.658

Jun16_preds <- predict(Jun16_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - Jun16_preds)^2)) # 14.462

#####---------------------------------
## Using May 2016 to predict June 2016
MayJun16_knn <- train(May16~Long0+Lat0, data = Jun16_Manhat, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
MayJun16_knn # k = 12, RMSE = 16.091, Rsq = 0.636

MayJun_preds <- predict(MayJun16_knn, newdata = Jun16_Manhat[,c(2,6,7)])
sqrt(mean((Jun16_Manhat$Jun16/4 - MayJun_preds/4)^2)) # RMSE = 20.642

MayJun_preds2 <- predict(MayJun16_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - MayJun_preds2)^2)) # RMSE = 9.437

#####-------------------------------------
## Using Average from 2009-2016: All Months

ndsub <- subset(nd09_16, subset = Lat >= 40.7 & Lat <= 40.84 & Lon >= -74.025 & Lon <= -73.92)
Jun16_Manhat$AllMeans <- rowMeans(ndsub[,-c(1,90:92)])
AllMeans_knn <- train(AllMeans~Long0+Lat0, data = Jun16_Manhat, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
AllMeans_knn # k = 8, RMSE = 14.133, Rsq = 0.737

AllMeans_preds <- predict(AllMeans_knn, newdata = Jun16_Manhat[,c(2,6,7)])
sqrt(mean((Jun16_Manhat$Jun16/4 - AllMeans_preds/4)^2)) # RMSE = 9.569

AllMeans_preds2 <- predict(AllMeans_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - AllMeans_preds2)^2)) # RMSE = 10.034

#####-------------------------------------
## Using Average from 2009-2016: June Only

Jun16_Manhat$JuneMeans <- rowMeans(ndsub[,c(7,19,31,43,55,66,78)])
JuneMeans_knn <- train(JuneMeans~Long0+Lat0, data = Jun16_Manhat, method = "knn",
                trControl = Jun16_control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")
JuneMeans_knn # k = 4, RMSE = 12.209, Rsq = 0.664

JuneMeans_preds <- predict(JuneMeans_knn, newdata = Jun16_Manhat[,c(2,6,7)])
sqrt(mean((Jun16_Manhat$Jun16/4 - JuneMeans_preds/4)^2)) # RMSE = 10.428

JuneMeans_preds2 <- predict(JuneMeans_knn, newdata = test_data)
sqrt(mean((test_data$Jun16 - JuneMeans_preds2)^2))


#####----------------------------------------------------------------------------
## Graphing Manhattan Only Predictions
#####----------------------------------------------------------------------------

zoom_map_raw <- get_map(location = c(-73.98, 40.76), zoom = 12, scale = 2)
zoom_map <- ggmap(zoom_map_raw, legend = "none")

Jun16_Manhat$AllMeans <- rowMeans(ndsub[,-c(1,90:92)])
control <- trainControl(method = "cv", number = 10, classProbs = TRUE)
AllMeans_knn <- train(AllMeans~Long0+Lat0, data = Jun16_Manhat, method = "knn",
                trControl = control, tuneGrid = expand.grid(k = c(4,8,12,20,24)), metric = "RMSE")

Jun16_Manhat$JunePreds <- predict(AllMeans_knn, newdata = Jun16_Manhat[,c(2,6,7)])

Jun16_Manhat$obscolor <- cut(Jun16_Manhat$Jun16,
                          breaks = c(-300, -15,-4,0,3,200),
                          labels = c("(-77,-6)", "(-5,-1)", 0, "(1,5)", "(6,67)"))
Jun16_Manhat$predcolor <- cut(Jun16_Manhat$JunePreds,
                          breaks = c(-300, -14.5,-3,0.001,14.5,200),
                          labels = c("(-77,-6)", "(-5,-1)", 0, "(1,5)", "(6,67)"))


manh_obs_map <- zoom_map + geom_point(data = Jun16_Manhat, size = 0.7, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = obscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("Observed Net Pickups for Manhattan: Monday 12-1PM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 10, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 6))

manh_pred_map <- zoom_map + geom_point(data = Jun16_Manhat, size = 0.7, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = predcolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("Predicted Net Pickups for Manhattan: Monday 12-1PM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 10, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 6))

manh_obs_map; manh_pred_map

ggsave(filename = "Images/Manhattan_ObsNetMap", plot = manh_obs_map,
       width = 6, height = 6, device = "jpeg")
ggsave(filename = "Images/Manhattan_PredNetMap", plot = manh_pred_map,
       width = 6, height = 6, device = "jpeg")
```







