---
title: "Mon12_Compiling"
author: "Aidan Mullan"
date: "3/27/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Load required packages
library(rvest)
library(xml2)
library(magrittr)
library(stringr)
library(tidyr)
library(ggplot2)
library(ggmap)
library(gridExtra)
library(cowplot)
library(devtools)
library(tidyverse)
library(geohash)
```


```{r}
URL <- "https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page"

links <- read_html(URL) %>% html_nodes("a") %>% html_attr('href')

yellow_index <- str_detect(links, "yellow_tripdata")
yellow_data <- links[yellow_index][25:120][c(1:6,13:120)][1:90]
chrono <- rev(c(30:19,42:31,54:43,66:55,78:67))
yellow09 <- yellow_data[79:90]
yellow1516 <- yellow_data[c(7:18,1:6)]
yellow1014 <- yellow_data[chrono]
```

```{r}
full_counts <- data.frame(geohash = NA)
i = 1

for(link in yellow09){
  link <- yellow09[i]
  raw_data <- read.csv(link)
  short_data <- raw_data[,c(2,3,6,7,10,11)]
  firstsplit <- short_data %>% separate(Trip_Pickup_DateTime, sep = " ", n = 2,
                                                 into = c("pickup_date", "pickup_time")) %>%
                                        separate(Trip_Dropoff_DateTime, sep = " ", n = 2,
                                                 into = c("dropoff_date", "dropoff_time"))
  firstsplit$PU_weekday <- weekdays(as.Date(firstsplit$pickup_date))
  firstsplit$DO_weekday <- weekdays(as.Date(firstsplit$dropoff_date))
  clean_data <- firstsplit %>% separate(pickup_time, sep = ":", n = 3,
                                                  into = c("PU_hour", "PU_minute", "PU_second")) %>%
                                         separate(pickup_date, sep = "-", n = 3,
                                                  into = c("PU_year", "PU_month", "PU_day")) %>%
                                         separate(dropoff_time, sep = ":", n = 3,
                                                  into = c("DO_hour", "DO_minute", "DO_second")) %>%
                                         separate(dropoff_date, sep = "-", n = 3,
                                                  into = c("DO_year", "DO_month", "DO_day"))
  
  
  pu_data_raw <- subset(clean_data, subset = PU_hour == 12 & PU_weekday == "Monday")
  pu_data <- pu_data_raw[,c(1:6,9,13,14,17)]
  pu_data$pickup_latitude <- pu_data$Start_Lat
  pu_data$pickup_longitude <- pu_data$Start_Lon
  pu_clean <- subset(pu_data, subset = pickup_latitude != 0 & pickup_longitude != 0)
  
  lat_mid <- quantile(pu_clean$pickup_latitude, probs = c(.0005, 0.9995))
  lon_mid <- quantile(pu_clean$pickup_longitude, probs = c(.0005, 0.9995))

  pu_main <- subset(pu_clean, subset = pickup_latitude > lat_mid[[1]] & pickup_latitude < lat_mid[[2]])
  pu_main <- subset(pu_main, subset = pickup_latitude > lat_mid[[1]] &
                      pickup_latitude < lat_mid[[2]])
  pu_main$geohash <- geohash::gh_encode(lats = pu_main$pickup_latitude,
                                          lngs = pu_main$pickup_longitude,
                                   precision = 7)
  pu_counts <- pu_main %>% group_by(geohash, PU_day) %>% summarise(pickups = n())
  
  do_data_raw <- subset(clean_data, subset = DO_hour == 12 & DO_weekday == "Monday")
  do_data <- do_data_raw[,c(7:12,15,16,18)]
  do_data$dropoff_latitude <- do_data$End_Lat
  do_data$dropoff_longitude <- do_data$End_Lon
  do_clean <- subset(do_data, subset = dropoff_latitude != 0 & dropoff_longitude != 0)

  do_main <- subset(do_clean, subset = dropoff_latitude > lat_mid[[1]] & dropoff_latitude < lat_mid[[2]])
  do_main <- subset(do_main, subset = dropoff_latitude > lat_mid[[1]] &
                      dropoff_latitude < lat_mid[[2]])
  do_main$geohash <- geohash::gh_encode(lats = do_main$dropoff_latitude,
                                        lngs = do_main$dropoff_longitude, precision = 7)
  do_counts <- do_main %>% group_by(geohash) %>% summarise(dropoffs = n())
  
  all_counts <- merge(pu_counts, do_counts, by = "geohash", all = TRUE)
  all_counts$pickups <- ifelse(is.na(all_counts$pickups), 0, all_counts$pickups)
  all_counts$dropoffs <- ifelse(is.na(all_counts$dropoffs), 0, all_counts$dropoffs)
  all_counts$netdiff <- all_counts$pickups - all_counts$dropoffs
  final_counts <- data.frame(geohash = all_counts$geohash, netdiff = all_counts$netdiff)
  full_counts <- merge(full_counts, final_counts, by.x = "geohash", by.y = "geohash",
                       all.y = TRUE, suffixes = c("", i))
  duplicates <- duplicated(full_counts$geohash)
  full_counts <- full_counts[!duplicates,]
  i = i+1

  rm(raw_data); rm(short_data); rm(firstsplit); rm(clean_data)
  rm(pu_data_raw); rm(pu_data); rm(pu_clean); rm(pu_main); rm(pu_counts)
  rm(do_data_raw); rm(do_data); rm(do_clean); rm(do_main); rm(do_counts)
  rm(all_counts); rm(final_counts)
}

for(link in yellow1014){
  raw_data <- read.csv(link)
  short_data <- raw_data[,c(2,3,6,7,10,11)]
  firstsplit <- short_data %>% separate(pickup_datetime, sep = " ", n = 2,
                                                 into = c("pickup_date", "pickup_time")) %>%
                                        separate(dropoff_datetime, sep = " ", n = 2,
                                                 into = c("dropoff_date", "dropoff_time"))
  firstsplit$PU_weekday <- weekdays(as.Date(firstsplit$pickup_date))
  firstsplit$DO_weekday <- weekdays(as.Date(firstsplit$dropoff_date))
  clean_data <- firstsplit %>% separate(pickup_time, sep = ":", n = 3,
                                                  into = c("PU_hour", "PU_minute", "PU_second")) %>%
                                         separate(pickup_date, sep = "-", n = 3,
                                                  into = c("PU_year", "PU_month", "PU_day")) %>%
                                         separate(dropoff_time, sep = ":", n = 3,
                                                  into = c("DO_hour", "DO_minute", "DO_second")) %>%
                                         separate(dropoff_date, sep = "-", n = 3,
                                                  into = c("DO_year", "DO_month", "DO_day"))
  
  
  pu_data_raw <- subset(clean_data, subset = PU_hour == 12 & PU_weekday == "Monday")
  pu_data <- pu_data_raw[,c(1:6,9,13,14,17)]
  pu_clean <- subset(pu_data, subset = pickup_latitude != 0 & pickup_longitude != 0)
  
  lat_mid <- quantile(pu_clean$pickup_latitude, probs = c(.0005, 0.9995))
  lon_mid <- quantile(pu_clean$pickup_longitude, probs = c(.0005, 0.9995))

  pu_main <- subset(pu_clean, subset = pickup_latitude > lat_mid[[1]] & pickup_latitude < lat_mid[[2]])
  pu_main <- subset(pu_main, subset = pickup_latitude > lat_mid[[1]] &
                      pickup_latitude < lat_mid[[2]])
  pu_main$geohash <- geohash::gh_encode(lats = pu_main$pickup_latitude,
                                          lngs = pu_main$pickup_longitude,
                                   precision = 7)
  pu_counts <- pu_main %>% group_by(geohash, PU_day) %>% summarise(pickups = n())
  
  do_data_raw <- subset(clean_data, subset = DO_hour == 12 & DO_weekday == "Monday")
  do_data <- do_data_raw[,c(7:12,15,16,18)]
  do_clean <- subset(do_data, subset = dropoff_latitude != 0 & dropoff_longitude != 0)

  do_main <- subset(do_clean, subset = dropoff_latitude > lat_mid[[1]] & dropoff_latitude < lat_mid[[2]])
  do_main <- subset(do_main, subset = dropoff_latitude > lat_mid[[1]] &
                      dropoff_latitude < lat_mid[[2]])
  do_main$geohash <- geohash::gh_encode(lats = do_main$dropoff_latitude,
                                        lngs = do_main$dropoff_longitude, precision = 7)
  do_counts <- do_main %>% group_by(geohash) %>% summarise(dropoffs = n())
  
  all_counts <- merge(pu_counts, do_counts, by = "geohash", all = TRUE)
  all_counts$pickups <- ifelse(is.na(all_counts$pickups), 0, all_counts$pickups)
  all_counts$dropoffs <- ifelse(is.na(all_counts$dropoffs), 0, all_counts$dropoffs)
  all_counts$netdiff <- all_counts$pickups - all_counts$dropoffs
  final_counts <- data.frame(geohash = all_counts$geohash, netdiff = all_counts$netdiff)
  full_counts <- merge(full_counts, all_counts[,c(1,4)], by = "geohash", all = TRUE, suffixes = c("", i))
  i = i+1
  i
  rm(raw_data); rm(short_data); rm(firstsplit); rm(clean_data)
  rm(pu_data_raw); rm(pu_data); rm(pu_clean); rm(pu_main); rm(pu_counts)
  rm(do_data_raw); rm(do_data); rm(do_clean); rm(do_main); rm(do_counts)
  rm(all_counts); rm(final_counts)
}



for(link in yellow1516){
  raw_data <- read.csv(link)
  short_data <- raw_data[,c(2,3,6,7,10,11)]
  firstsplit <- short_data %>% separate(tpep_pickup_datetime, sep = " ", n = 2,
                                                 into = c("pickup_date", "pickup_time")) %>%
                                        separate(tpep_dropoff_datetime, sep = " ", n = 2,
                                                 into = c("dropoff_date", "dropoff_time"))
  firstsplit$PU_weekday <- weekdays(as.Date(firstsplit$pickup_date))
  firstsplit$DO_weekday <- weekdays(as.Date(firstsplit$dropoff_date))
  clean_data <- firstsplit %>% separate(pickup_time, sep = ":", n = 3,
                                                  into = c("PU_hour", "PU_minute", "PU_second")) %>%
                                         separate(pickup_date, sep = "-", n = 3,
                                                  into = c("PU_year", "PU_month", "PU_day")) %>%
                                         separate(dropoff_time, sep = ":", n = 3,
                                                  into = c("DO_hour", "DO_minute", "DO_second")) %>%
                                         separate(dropoff_date, sep = "-", n = 3,
                                                  into = c("DO_year", "DO_month", "DO_day"))
  
  
  pu_data_raw <- subset(clean_data, subset = PU_hour == 12 & PU_weekday == "Monday")
  pu_data <- pu_data_raw[,c(1:6,9,13,14,17)]
  pu_clean <- subset(pu_data, subset = pickup_latitude != 0 & pickup_longitude != 0)
  
  lat_mid <- quantile(pu_clean$pickup_latitude, probs = c(.0005, 0.9995))
  lon_mid <- quantile(pu_clean$pickup_longitude, probs = c(.0005, 0.9995))

  pu_main <- subset(pu_clean, subset = pickup_latitude > lat_mid[[1]] & pickup_latitude < lat_mid[[2]])
  pu_main <- subset(pu_main, subset = pickup_latitude > lat_mid[[1]] &
                      pickup_latitude < lat_mid[[2]])
  pu_main$geohash <- geohash::gh_encode(lats = pu_main$pickup_latitude,
                                          lngs = pu_main$pickup_longitude,
                                   precision = 7)
  pu_counts <- pu_main %>% group_by(geohash, PU_day) %>% summarise(pickups = n())
  
  do_data_raw <- subset(clean_data, subset = DO_hour == 12 & DO_weekday == "Monday")
  do_data <- do_data_raw[,c(7:12,15,16,18)]
  do_clean <- subset(do_data, subset = dropoff_latitude != 0 & dropoff_longitude != 0)

  do_main <- subset(do_clean, subset = dropoff_latitude > lat_mid[[1]] & dropoff_latitude < lat_mid[[2]])
  do_main <- subset(do_main, subset = dropoff_latitude > lat_mid[[1]] &
                      dropoff_latitude < lat_mid[[2]])
  do_main$geohash <- geohash::gh_encode(lats = do_main$dropoff_latitude,
                                        lngs = do_main$dropoff_longitude, precision = 7)
  do_counts <- do_main %>% group_by(geohash) %>% summarise(dropoffs = n())
  
  all_counts <- merge(pu_counts, do_counts, by = "geohash", all = TRUE)
  all_counts$pickups <- ifelse(is.na(all_counts$pickups), 0, all_counts$pickups)
  all_counts$dropoffs <- ifelse(is.na(all_counts$dropoffs), 0, all_counts$dropoffs)
  all_counts$netdiff <- all_counts$pickups - all_counts$dropoffs
  final_counts <- data.frame(geohash = all_counts$geohash, netdiff = all_counts$netdiff)
  full_counts <- merge(full_counts, all_counts[,c(1,4)], by = "geohash", all = TRUE, suffixes = c("", i))
  i = i+1
  i
  rm(raw_data); rm(short_data); rm(firstsplit); rm(clean_data)
  rm(pu_data_raw); rm(pu_data); rm(pu_clean); rm(pu_main); rm(pu_counts)
  rm(do_data_raw); rm(do_data); rm(do_clean); rm(do_main); rm(do_counts)
  rm(all_counts); rm(final_counts)
}
```

2009: Col 2,3,6,7,10,11
Trip_Pickup_DateTime YYYY-MM-DD HH:MM:SS
Trip_Dropoff_DateTime YYYY-MM-DD HH:MM:SS
Start_Lon
Start_Lat
End_Lon
End_Lat

2010-2014: Col 2,3,6,7,10,11
pickup_datetime
dropoff_datetime
pickup_longitude
pickup_latitude
dropoff_longitude
dropoff_latitude

2016: Col 2,3,6,7,10,11
tpep_pickup_datetime
tpep_dropoff_datetime
pickup_longitude
pickup_latitude
dropoff_longitude
dropoff_latitude

```{r}
full_counts <- data.frame(geohash = NA)
for(i in 67:78){
  link <- yellow_data[i]
  raw_data <- read.csv(link)
  short_data <- raw_data[,c(2,3,6,7,10,11)]
  firstsplit <- short_data %>% separate(pickup_datetime, sep = " ", n = 2,
                                                 into = c("pickup_date", "pickup_time")) %>%
                                        separate(dropoff_datetime, sep = " ", n = 2,
                                                 into = c("dropoff_date", "dropoff_time"))
  firstsplit$PU_weekday <- weekdays(as.Date(firstsplit$pickup_date))
  firstsplit$DO_weekday <- weekdays(as.Date(firstsplit$dropoff_date))
  clean_data <- firstsplit %>% separate(pickup_time, sep = ":", n = 3,
                                                  into = c("PU_hour", "PU_minute", "PU_second")) %>%
                                         separate(pickup_date, sep = "-", n = 3,
                                                  into = c("PU_year", "PU_month", "PU_day")) %>%
                                         separate(dropoff_time, sep = ":", n = 3,
                                                  into = c("DO_hour", "DO_minute", "DO_second")) %>%
                                         separate(dropoff_date, sep = "-", n = 3,
                                                  into = c("DO_year", "DO_month", "DO_day"))
  
  
  pu_data_raw <- subset(clean_data, subset = PU_hour == 12 & PU_weekday == "Monday")
  pu_data <- pu_data_raw[,c(1:6,9,13,14,17)]
  pu_clean <- subset(pu_data, subset = pickup_latitude != 0 & pickup_longitude != 0)
  
  lat_mid <- quantile(pu_clean$pickup_latitude, probs = c(.0005, 0.9995))
  lon_mid <- quantile(pu_clean$pickup_longitude, probs = c(.0005, 0.9995))

  pu_main <- subset(pu_clean, subset = pickup_latitude > lat_mid[[1]] & pickup_latitude < lat_mid[[2]])
  pu_main <- subset(pu_main, subset = pickup_latitude > lat_mid[[1]] &
                      pickup_latitude < lat_mid[[2]])
  pu_main$geohash <- geohash::gh_encode(lats = pu_main$pickup_latitude,
                                          lngs = pu_main$pickup_longitude,
                                   precision = 7)
  pu_counts <- pu_main %>% group_by(geohash, PU_day) %>% summarise(pickups = n())
  
  do_data_raw <- subset(clean_data, subset = DO_hour == 12 & DO_weekday == "Monday")
  do_data <- do_data_raw[,c(7:12,15,16,18)]
  do_clean <- subset(do_data, subset = dropoff_latitude != 0 & dropoff_longitude != 0)

  do_main <- subset(do_clean, subset = dropoff_latitude > lat_mid[[1]] & dropoff_latitude < lat_mid[[2]])
  do_main <- subset(do_main, subset = dropoff_latitude > lat_mid[[1]] &
                      dropoff_latitude < lat_mid[[2]])
  do_main$geohash <- geohash::gh_encode(lats = do_main$dropoff_latitude,
                                        lngs = do_main$dropoff_longitude, precision = 7)
  do_counts <- do_main %>% group_by(geohash) %>% summarise(dropoffs = n())
  
  all_counts <- merge(pu_counts, do_counts, by = "geohash", all = TRUE)
  all_counts$pickups <- ifelse(is.na(all_counts$pickups), 0, all_counts$pickups)
  all_counts$dropoffs <- ifelse(is.na(all_counts$dropoffs), 0, all_counts$dropoffs)
  all_counts$netdiff <- all_counts$pickups - all_counts$dropoffs
  final_counts <- data.frame(geohash = all_counts$geohash, netdiff = all_counts$netdiff)
  full_counts <- merge(full_counts, final_counts, by.x = "geohash", by.y = "geohash",
                       all.y = TRUE, suffixes = c("", i))
  duplicates <- duplicated(full_counts$geohash)
  full_counts <- full_counts[!duplicates,]
  
  rm(raw_data); rm(short_data); rm(firstsplit); rm(clean_data)
  rm(pu_data_raw); rm(pu_data); rm(pu_clean); rm(pu_main); rm(pu_counts)
  rm(do_data_raw); rm(do_data); rm(do_clean); rm(do_main); rm(do_counts)
  rm(all_counts); rm(final_counts)
}
```

