---
title: "Early_Images"
author: "Aidan Mullan"
date: "5/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Load required packages
library(caret)
library(dplyr)
library(e1071)
library(geohash)
library(stringr)
library(ggplot2)
library(ggmap)

geohashes <- read.csv("Data/geohashes.csv")
```

```{r, fig.height = 5, fig.width = 5}
full_data <- read.csv("Data/Mon08_Predicts.csv")
geohashes <- read.csv("Data/geohashes.csv")

Man_index <- which(full_data$geohash %in% geohashes$geohash)
sub_data <- full_data[Man_index,]

hashes <- gh_decode(sub_data$geohash)
sub_data$Lat <- hashes$lat
sub_data$Lon <- hashes$lng
sub_data$lowbound <- sub_data$Lat - 1.6*sub_data$Lon
sub_data$upbound <- sub_data$Lat - 1.454545*sub_data$Lat
predict_data <- subset(sub_data, subset = lowbound >= 159.064 & upbound <= 148.4327)


predict_data$obscolor <- cut(predict_data$observed,
                          breaks = c(-100, -5,-1,0,5,100),
                          labels = c("(-55,-6)", "(-5,-1)", "0", "(1,5)", "(6,58)"))
predict_data$knncolor <- cut(predict_data$knn_predict,
                          breaks = c(-100, -5,-1,0.5,5,100),
                          labels = c("(-33,-6)", "(-5,-1)", "0", "(1,5)", "(6,22)"))
predict_data$tscolor <- cut(predict_data$smooth_predict,
                          breaks = c(-100, -5,-1,0.5,5,100),
                          labels = c("(-52,-6)", "(-5,-1)", "0", "(1,5)", "(6,55)"))
predict_data$armacolor <- cut(predict_data$arima_predict,
                          breaks = c(-100, -5,-1,0.5,5,100),
                          labels = c("(-52,-6)", "(-5,-1)", "0", "(1,5)", "(6,55)"))

zoom_map_raw <- get_map(location = c(-73.98, 40.76), zoom = 12, scale = 2)
zoom_map <- ggmap(zoom_map_raw, legend = "none")

obs_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = obscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("Manhattan Observed Net Pickups: June 20th, 2016 at 10am") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

knn_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = knncolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("KNN Predicted Net Pickups for Manhattan: Mon 8AM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

ts_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = tscolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("Exponential Smoothing Predicted Net Pickups for Manhattan: Mon 8AM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

arma_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = armacolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("ARIMA Predicted Net Pickups: June 20th, 2016 at 10") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

cor(predict_data$observed, predict_data$knn_predict)^2 # .50406
cor(predict_data$observed, predict_data$smooth_predict)^2 # .90753
cor(predict_data$observed, predict_data$arima_predict)^2 # .90149
sqrt(mean((predict_data$observed - predict_data$knn_predict)^2)) # 3.1475
sqrt(mean((predict_data$observed - predict_data$smooth_predict)^2)) # 1.3674
sqrt(mean((predict_data$observed - predict_data$arima_predict)^2)) # 1.4307

ggsave(filename = "Images/Mon8_ObsMap.jpeg", plot = obs_map,
       width = 7, height = 7, device = "jpeg")
ggsave(filename = "Images/Mon8_KnnMap.jpeg", plot = knn_map,
       width = 7, height = 7, device = "jpeg")
ggsave(filename = "Images/Mon8_TsMap.jpeg", plot = ts_map,
       width = 7, height = 7, device = "jpeg")
ggsave(filename = "Images/Mon8_ARMAMap.jpeg", plot = arma_map,
       width = 7, height = 7, device = "jpeg")

par(mfrow = c(2,2))
plot(predict_data$observed, predict_data$observed - predict_data$smooth_predict, xlab = "Net-Pickups",
     ylab = "Residual", main = "HW Smoothing Model Residuals")
plot(predict_data$observed, predict_data$observed - predict_data$arima_predict, xlab = "Net-Pickups",
     ylab = "Residual", main = "ARMA Residuals")
plot(predict_data$observed, predict_data$observed - predict_data$knn_predict, xlab = "Net-Pickups",
     ylab = "Residual", main = "KNN Residuals")
qqnorm(obs-quad_preds)
qqline(obs-quad_preds)

```

```{r}
predict_data$knn_resid <- predict_data$observed - predict_data$knn_predict
predict_data$arima_resid <- predict_data$observed - predict_data$arima_predict
predict_data$smooth_resid <- predict_data$observed - predict_data$smooth_predict

summary(predict_data$knn_resid)
summary(predict_data$arima_resid)
summary(predict_data$smooth_resid)

predict_data$knn_rescolor <- cut(predict_data$knn_resid,
                          breaks = c(-100, -3,-0.5,0.5,3,100),
                          labels = c("(-38,-3)", "(-3,-1)", "0", "(1,3)", "(3,41)"))
predict_data$arima_rescolor <- cut(predict_data$arima_resid,
                          breaks = c(-100, -3,-0.5,0.5,3,100),
                          labels = c("(-10,-3)", "(-3,-1)", "0", "(1,3)", "(3,16)"))
predict_data$smooth_rescolor <- cut(predict_data$smooth_resid,
                          breaks = c(-100, -3,-0.5,0.5,3,100),
                          labels = c("(-10,-3)", "(-3,-1)", "0", "(1,3)", "(3,17)"))

knn_res_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = knn_rescolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("KNN Residuals for Manhattan: Mon 8AM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

arma_res_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = arima_rescolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("ARIMA Residuals for Manhattan: Mon 8AM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

smooth_res_map <- zoom_map + geom_point(data = predict_data, size = 0.9, na.rm = TRUE, shape = 15,
                                       aes(x = Lon, y = Lat, color = smooth_rescolor)) + 
  scale_color_manual(values = c("darkred", "lightcoral", "grey", "dodgerblue", "navyblue"),
                     name = "Net Pickups") +
  ggtitle("HW Smoothing Residuals for Manhattan: Mon 8AM") +
  xlab("") + ylab("") +
  theme(axis.line = element_blank(), axis.text = element_blank(),
        axis.ticks = element_blank(), plot.title = element_text(size = 14, hjust = 0.5),
        legend.title = element_text(size = 8), legend.text = element_text(size = 9))

ggsave(filename = "Images/Mon8_KnnResMap.jpeg", plot = knn_res_map,
       width = 7, height = 7, device = "jpeg")
ggsave(filename = "Images/Mon8_TsResMap.jpeg", plot = smooth_res_map,
       width = 7, height = 7, device = "jpeg")
ggsave(filename = "Images/Mon8_ARMAResMap.jpeg", plot = arma_res_map,
       width = 7, height = 7, device = "jpeg")
```


```{r, fig.height = 3, fig.width = 6}
knn_r2 <- read.csv("Data/Results/knn_r2.csv")[,-1]
arima_r2 <- read.csv("Data/Results/arima_r2.csv")[,-1]
smooth_r2 <- read.csv("Data/Results/expsmooth_r2.csv")[,-1]
knn_rmse <- read.csv("Data/Results/knn_rmse.csv")[,-1]
arima_rmse <- read.csv("Data/Results/arima_rmse.csv")[,-1]
smooth_rmse <- read.csv("Data/Results/expsmooth_rmse.csv")[,-1]

colMeans(knn_r2)
colMeans(arima_r2)
colMeans(smooth_r2)

colMeans(knn_rmse)
colMeans(arima_rmse)
colMeans(smooth_rmse)

median(smooth_rmse)
max(smooth_rmse)
mean(colMeans(smooth_r2))
mean(colMeans(smooth_rmse))

par(mfrow = c(1,2))
plot(rowMeans(knn_r2)~seq(0,23.5, 0.5), type = "l", ylim = c(0,1), xlab = "Hour", ylab = expression(R^2),
     main = bquote("Mean"~R^2~"by Time of Day"))
lines(rowMeans(arima_r2)~seq(0,23.5, 0.5), col = "dodgerblue")
lines(rowMeans(smooth_r2)~seq(0,23.5, 0.5), col = "navyblue")
legend("bottomleft", legend = c("KNN", "ARMA", "HW Smoothing"), col = c("black", "dodgerblue", "navyblue"),
       lty = 1)
points(rowMeans(knn_r2)~seq(0,23.5, 0.5), pch = 16, cex = 0.7)
points(rowMeans(arima_r2)~seq(0,23.5, 0.5), pch = 16, col = "dodgerblue", cex = 0.7)
points(rowMeans(smooth_r2)~seq(0,23.5, 0.5), pch = 16, col = "navyblue", cex = 0.7)

plot(rowMeans(knn_rmse)~seq(0,23.5, 0.5), type = "l", ylim = c(0,6), xlab = "Hour", ylab = "RMSE",
     main = bquote("Mean RMSE by Time of Day"), xlim = c(0,24), font.main = 1)
lines(rowMeans(arima_rmse)~seq(0,23.5, 0.5), col = "dodgerblue")
lines(rowMeans(smooth_rmse)~seq(0,23.5, 0.5), col = "navyblue")
legend("topright", legend = c("KNN", "ARMA", "HW Smoothing"), col = c("black", "dodgerblue", "navyblue"),
       lty = 1)
points(rowMeans(knn_rmse)~seq(0,23.5, 0.5), pch = 16, cex = 0.7)
points(rowMeans(arima_rmse)~seq(0,23.5, 0.5), pch = 16, col = "dodgerblue", cex = 0.7)
points(rowMeans(smooth_rmse)~seq(0,23.5, 0.5), pch = 16, col = "navyblue", cex = 0.7)

plot(1:7,as.numeric(colMeans(knn_r2)), type = "l", ylim = c(0.2,0.9), xlab = "Day", ylab = expression(R^2),
     main = bquote("Mean"~R^2~"by Day of the Week"), xaxt = "n")
lines(as.numeric(colMeans(arima_r2)), col = "dodgerblue")
lines(as.numeric(colMeans(smooth_r2)), col = "navyblue")
legend("bottomleft", legend = c("KNN", "ARMA", "HW Smoothing"), col = c("black", "dodgerblue", "navyblue"),
       lty = 1)
points(1:7,as.numeric(colMeans(knn_r2)), pch = 16)
points(1:7,as.numeric(colMeans(arima_r2)), col = "dodgerblue", pch = 16)
points(1:7,as.numeric(colMeans(smooth_r2)), col = "navyblue", pch = 16)
axis(1, labels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),
     at = 1:7, cex.axis = 0.7)

plot(1:7,as.numeric(colMeans(knn_rmse)), type = "l", ylim = c(0,4), xlab = "Day", ylab = expression(R^2),
     main = bquote("Mean RMSE by Day of the Week"), xaxt = "n", font.main = 1)
lines(as.numeric(colMeans(arima_rmse)), col = "dodgerblue")
lines(as.numeric(colMeans(smooth_rmse)), col = "navyblue")
legend("bottomleft", legend = c("KNN", "ARMA", "HW Smoothing"), col = c("black", "dodgerblue", "navyblue"),
       lty = 1)
points(1:7,as.numeric(colMeans(knn_rmse)), pch = 16)
points(1:7,as.numeric(colMeans(arima_rmse)), col = "dodgerblue", pch = 16)
points(1:7,as.numeric(colMeans(smooth_rmse)), col = "navyblue", pch = 16)
axis(1, labels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),
     at = 1:7, cex.axis = 0.7)

par(mfrow = c(1,2))
plot(rowMeans(smooth_r2)~seq(0,23.5, 0.5), type = "l", ylim = c(0,1), xlab = "Hour", ylab = expression(R^2),
     main = bquote("Mean"~R^2~"and RMSE by Time of Day"), col = "navyblue")
points(rowMeans(smooth_r2)~seq(0,23.5, 0.5), pch = 16, col = "navyblue", cex = 0.7)
par(new = T)
plot(rowMeans(smooth_rmse)~seq(0,23.5, 0.5), type = "l", ylim = c(0,4), xlab = NA, ylab = NA,
     xlim = c(0,24), font.main = 1, col = "dodgerblue", axes = F)
axis(side = 4)
mtext(side = 4, line = 2, "RMSE")
points(rowMeans(smooth_rmse)~seq(0,23.5, 0.5), pch = 16, col = "dodgerblue", cex = 0.7)
legend("bottomright", legend = c(expression(R^2), "RMSE"), col = c("navyblue", "dodgerblue"), lty = 1)

par(mfrow =c(1,2))
plot(1:7,as.numeric(colMeans(smooth_r2)), type = "l", ylim = c(0.2,0.9), xlab = "Day",
     ylab = expression(R^2), main = bquote("Mean"~R^2~"and RMSE by Day of the Week"), xaxt = "n")
points(1:7,as.numeric(colMeans(smooth_r2)), col = "navyblue", pch = 16)
axis(1, labels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"),
     at = 1:7, cex.axis = 0.7)
par(new = T)
plot(1:7,as.numeric(colMeans(smooth_rmse)), type = "l", ylim = c(0,4), xlab = NA, ylab = NA,
     axes = F, font.main = 1, col = "dodgerblue")
points(1:7,as.numeric(colMeans(smooth_rmse)), col = "dodgerblue", pch = 16)
axis(side = 4)
mtext(side = 4, line = 2, "RMSE")
legend("bottomright", legend = c(expression(R^2), "RMSE"), col = c("navyblue", "dodgerblue"), lty = 1)
```

